server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json

spring.jpa.database: postgresql

# User Profile Database
spring.datasource.jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=userprofiles
spring.datasource.username: postgres
spring.datasource.password: readify
spring.datasource.platform: postgres
spring.datasource.driver-class-name: org.postgresql.Driver

# Search Database
spring.authentication.jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=authentication
spring.authentication.username: postgres
spring.authentication.password: readify
spring.authentication.platform: postgres
spring.authentication.driver-class-name: org.postgresql.Driver
