server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json

spring.jpa.database: postgresql

# User Profile Database
spring.datasource.jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=userprofiles
spring.datasource.username: postgres
spring.datasource.password: readify
spring.datasource.platform: postgres
spring.datasource.driver-class-name: org.postgresql.Driver

# Search Database
spring.search.jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=search
spring.search.username: postgres
spring.search.password: readify
spring.search.platform: postgres
spring.search.driver-class-name: org.postgresql.Driver
