server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json

spring.jpa.database: postgresql

# User Profile Database
spring.datasource.jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=userprofiles
spring.datasource.username: postgres
spring.datasource.password: readify
spring.datasource.platform: postgres
spring.datasource.driver-class-name: org.postgresql.Driver

# Authentication Database
spring.authentication.jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=authentication
spring.authentication.username: postgres
spring.authentication.password: readify
spring.authentication.platform: postgres
spring.authentication.driver-class-name: org.postgresql.Driver

# Book publishing Database
spring.bookpublishing.jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=bookpublishing
spring.bookpublishing.username: postgres
spring.bookpublishing.password: readify
spring.bookpublishing.platform: postgres
spring.bookpublishing.driver-class-name: org.postgresql.Driver


# Book publishing Database
spring.readerlibrary.jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=readerlibrary
spring.readerlibrary.username: postgres
spring.readerlibrary.password: readify
spring.readerlibrary.platform: postgres
spring.readerlibrary.driver-class-name: org.postgresql.Driver


# Book publishing Database
spring.search.jdbcUrl: jdbc:postgresql://localhost:5432/postgres?currentSchema=search
spring.search.username: postgres
spring.search.password: readify
spring.search.platform: postgres
spring.search.driver-class-name: org.postgresql.Driver

authentication:
  hmac256:
    secret: "secret"

stripe:
  domain: "http://localhost:4242"
  success: "public/success.html?session_id={CHECKOUT_SESSION_ID}"
  cancel: "public/canceled.html"
  secretKey: "sk_test_Q5cwflC6COQRLAixERlNCOXg00JszEtqVH"

management.endpoints.web.exposure.include: httptrace