version: '3'

services:
  postgresql:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: readify
    volumes:
      - ./src/userprofile/main/kotlin/resources/user-profile-init.sql:/docker-entrypoint-initdb.d/1-user-profiles-init.sql
      - ./src/authentication/main/kotlin/resources/authentication-init.sql:/docker-entrypoint-initdb.d/2-authentication-init.sql
      - ./src/bookpublishing/main/kotlin/resources/book-publishing-init.sql:/docker-entrypoint-initdb.d/2-bookpublishing-init.sql