version: '3'

services:
  postgres:
    container_name: userprofile-postgresql
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: readify
    volumes:
      - ./src/userprofile/main/kotlin/resources/init.sql:/docker-entrypoint-initdb.d/1-user-profiles-init.sql